# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concreteuserroleassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='concreteuserroleassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='concreteuserroleassignmentmultiplecontexts',
            name='role',
        ),
        migrations.RemoveField(
            model_name='concreteuserroleassignmentmultiplecontexts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='concreteuserroleassignmentnocontext',
            name='role',
        ),
        migrations.RemoveField(
            model_name='concreteuserroleassignmentnocontext',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConcreteUserRole',
        ),
        migrations.DeleteModel(
            name='ConcreteUserRoleAssignment',
        ),
        migrations.DeleteModel(
            name='ConcreteUserRoleAssignmentMultipleContexts',
        ),
        migrations.DeleteModel(
            name='ConcreteUserRoleAssignmentNoContext',
        ),
    ]
