
name: Tag and release

on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed

jobs:
  commitlint:
    uses: edx/.github/.github/workflows/tag-version.yml@jawayria/semantic-release
