name: Upgrade Requirements

on:
  push:
    branches:
      - '**'
  schedule:
     - cron: "45 1 * * 4"
  workflow_dispatch:
     inputs:
       branch:
         description: 'Target branch to create requirements PR against'
         required: true
         default: 'master'
jobs:
   call-upgrade-python-requirements-workflow:
    with:
       branch: ${{ github.event.inputs.branch }}
       team_reviewers: "arbi-bom"
       email_address: arbi-bom@edx.org
       send_success_notification: false
    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@jawayria/upgrade-workflow
